spring:
  datasource:
    username: hbstudent
    password: hbstudent
    url: jdbc:mysql://localhost:3306/uncovid
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9192