server:
  port: 8080 
  error:
    whitelabel:
      enabled: true

  
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      instance:
#        hostname: localhost
    
spring:
  datasource:
    username: root
    password: Amit@speaking@420
    url: jdbc:mysql://45.93.136.114:3306/uncovid
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: givehelpservice